### ISSUE TITLE
Failed to Save Settings on the Server

### ISSUE THREAD

**Issue by gisketch** [weedeej/ValorantCC#14]
So I have this set on the app
![image](https://user-images.githubusercontent.com/78424395/153867973-9e148b56-8f63-4ba7-8544-61d2e06cc7cd.png)

But when I play, the outline just turns black and says the error. 
![image](https://user-images.githubusercontent.com/78424395/153867840-c8fc2133-6f1e-4030-bdf2-5d6fc8507a42.png)
![image](https://user-images.githubusercontent.com/78424395/153867855-d1077152-9cac-43ad-95ab-e6f6b92944d4.png)

Any way around this?

**Comment by weedeej** [comment]
Can you send your logs here and the .OLD file?
