### ISSUE TITLE
ValorantCC is bannable

### ISSUE THREAD

**Issue by exdarku** [weedeej/ValorantCC#18]
For the first time, I used an external application for Valorant, which is ValorantCC yesterday.. This was my first time and I also know that no other applications are hooked and connected to Valorant. Logging in this morning, I found out that I was banned for using "prohibited third-party software"

Although I know it hurts as a developer to know this, ValorantCC is bannable. And it sucks having my main account banned and my pc HWID banned. I already contacted Riot about this, and hope they resolve this
![275326131_388464006429133_6197426549245958320_n](https://user-images.githubusercontent.com/47197960/160321275-a6e975f8-1c4f-4e06-9781-278afc74b3f9.png)
.

**Comment by weedeej** [comment]
Hi! I'm sorry to say this. But my Application for Official API where I mentioned ValorantCC was acknowledged. They ignored the fact that this was made. Additionally, ValorantCC does not change any gamefiles nor touch game memory. For information how it works, Please join the discord and read everything on Newcomers category. If you want, I can send a video here while I use the app rn.

**Comment by weedeej** [comment]
nvm, Imma just send the video here. The time of recording was March 28 2022 - 12:13pm Asia/Manila as time zone. Recorded using OBS Studio. [Proof that ValorantCC isn't Bannable](https://streamable.com/nzzyue)

**Comment by exdarku** [comment]
Do the application not break TOS?

**Comment by weedeej** [comment]
Does not in literal means. Riot Games is NOT against third party apps. Overwolf, Medal, TrackerGG, they're all 3rd party apps. Riot have nothing against third party devs. They even want to see what we can do with what we have. They can't also say whether an app is bannable or not as they do not know what the next update of ours will be.

**Comment by exdarku** [comment]
Alright, thanks for this. I've read your explanation in #how-does-it-work. But since the only third-party application I've been using for valorant is this, i'll take note and see if the ban is really because of this. Thank you!

**Comment by weedeej** [comment]
Alr. Thankyou for understanding. If you need further help or explanation, Feel free to ping me on the server.

**Comment by Mr7F** [comment]
@exdarku 
@weedeej 

Any news ? Was it because of ValorantCC or something else ?

**Comment by OzymoGit** [comment]
wait is it really bannable?

**Comment by exdarku** [comment]
My account did not get banned but my PC got banned for 4 months. Im pretty sure I have no other application possibly modifying the Valorant than ValorantCC. Better be safe than sorry though.

**Comment by weedeej** [comment]
> My account did not get banned but my PC got banned for 4 months. Im pretty sure I have no other application possibly modifying the Valorant than ValorantCC. Better be safe than sorry though.

ValorantCC does not even modify Valorant

**Comment by studsonyk** [comment]
@exdarku 4 months? in the picture it says permanently banned...

**Comment by exdarku** [comment]
Yep, I contacted them and said that my account weren't banned, but my PC was. So I waited for 4 months. I've been grinding now since I've been unbanned last July 28.

I did not remove anything in my pc except ValorantCC, and I'm not banned so far, so I'm still standing with what I said.

**Comment by sqshq666** [comment]
Well then sorry for your ban, I hope the issue will be fixed.
Then I guess getting banned for a crosshair is really not worth it. Will not use it anytime soon.
What is weird is that they don't ban Overwolf softwares or Discord overlay etc...

**Comment by weedeej** [comment]
Funny thing is: ValorantCC is only communicating Valorant, server side. If your account wasn't banned. But your PC. Imma say that's cappa.
