### ISSUE TITLE
App resets movement keybinds

### ISSUE THREAD

**Issue by Rayjacker** [weedeej/ValorantCC#21]
For some reason, whenever I use ValorantCC, my movement keys go from my normal ZQSD keys back to the default WASD keybinds.

**Comment by weedeej** [comment]
Can u send me your logs? both .old and the .txt

**Comment by Rayjacker** [comment]
I'd love to, but where would these logs be located? There are no log files in the app's directory.

Edit: After looking on the Discord for the log location, here are the files : 
[logs-old.txt](https://github.com/weedeej/ValorantCC/files/8549770/logs-old.txt)
[logs.txt](https://github.com/weedeej/ValorantCC/files/8549773/logs.txt)

**Comment by Enxivity** [comment]
same issue here

**Comment by weedeej** [comment]
Hi. I dug deeper and can't seem to find the cause. I'll update the app right away if I managed to fix it. for now, Please do bear with it.

**Comment by weedeej** [comment]
no response received from thread starter.
