### ISSUE TITLE
Not all colors work properly. 

### ISSUE THREAD

**Issue by HugoPfeffer** [weedeej/ValorantCC#22]
Some colors like dark green won't work in game. After saving and restarting the game. The crosshair keeps at light green. Purple and Orange don't work either. 

I'm not sure if it's a limitation on Riot's API or a bug.

**Comment by weedeej** [comment]
Yes. Valorant seems to render colors in their lighter versions. Blue looks like sky blue in-game so users selects Dark blue instead.
