### ISSUE TITLE
when i open .exe archive the program doesnt open

### ISSUE THREAD

**Issue by xRaionx** [weedeej/ValorantCC#23]
i used valorant cc for a long time but yesterday i updated it and now i cant open it, when i click in the .exe archive, the program doesnt open, even with administrator or with compatibility mode, i delated it and dowload it again but got the same problem. i also have disables the antivirus and i updated everything in the operative system and also in nvidia graphics
I use windows 10

**Comment by gobuster** [comment]
> i used valorant cc for a long time but yesterday i updated it and now i cant open it, when i click in the .exe archive, the program doesnt open, even with administrator or with compatibility mode, i delated it and dowload it again but got the same problem. i also have disables the antivirus and i updated everything in the operative system and also in nvidia graphics I use windows 10

You need to install the Runtime. You can install it from the link below or join the Discord where you can find it in #general-help
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.2-windows-x64-installer

**Comment by weedeej** [comment]
No response from thread starter.
