### ISSUE TITLE
switching colors doesnt work

### ISSUE THREAD

**Issue by Teraisu** [weedeej/ValorantCC#24]
when switching color of crosshair the game resets back to its original color after clicking save

**Comment by gobuster** [comment]
> when switching color of crosshair the game resets back to its original color after clicking save

You need to install the Runtime. You can install it from the link below or join the Discord where you can find it in #general-help
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.2-windows-x64-installer
