### ISSUE TITLE
Temp Banned for "Prohibited Game Modification" 

### ISSUE THREAD

**Issue by ArtByFen** [weedeej/ValorantCC#26]
This is the only possible thing that would be considered game modification that I've ever done. 
Use at your own risk.

**Comment by weedeej** [comment]
If you can read C#, you can see that the app does not modify any game files. it uses HTTP Requests to communicate with Riot Servers.

**Comment by ArtByFen** [comment]
Riot had a huge temp ban wave for a lot of small third party tools. 
Like I said this is the only thing I'm currently using. 

Riot on some dumb shit rn lmao.

**Comment by weedeej** [comment]
Blame it on this all you want. But as I am saying. ValorantCC does not modify any game files. :)
