### ISSUE TITLE
ValorantCC won't open(runtime is installed)

### ISSUE THREAD

**Issue by zozolea** [weedeej/ValorantCC#27]
(I have runtime installed)When I try to open it , it doesn't work also doesn't show up on task manager I tried uninstalling and reinstalling Val cc and runtime program multiple times and I have the same issue, it won't open . Help pls?

**Comment by weedeej** [comment]
Please join the discord so the community can help with the issue too.

**Comment by Blood323** [comment]
valorant cc crashes on open everytime i start it

**Comment by weedeej** [comment]
> valorant cc crashes on open everytime i start it

Open a new issue.

**Comment by weedeej** [comment]
No response received from thread starter.
