### ISSUE TITLE
ValorantCC doesn't seem to change the crosshair color post 08/09/2022 update

### ISSUE THREAD

**Issue by carbonfizz** [weedeej/ValorantCC#28]
The crosshair goes back to a default color post update automatically, and trying to change the color again doesn't fix the problem.

**Comment by lunncode** [comment]
I have the same problem.

**Comment by kavachi666** [comment]
Same.

**Comment by unprofessionalGamer** [comment]
please fix this i cant use any color but purple anymore ive grown to dependent plz fix fast my eyes hurt

**Comment by unprofessionalGamer** [comment]
also my ads crosshair works but not my sniper or primary

**Comment by clawzt** [comment]
please fix please my aim is turn into a gufy aaaaaaaaahhhhhh aim

**Comment by weedeej** [comment]
Please do try to reach out on us on discord. Discussions here are not watched as much as discussions on the Discord server.

**Comment by KUSHIW00SHIE** [comment]
> Please do try to reach out on us on discord. Discussions here are not watched as much as discussions on the Discord server.

I have joined the discord but I still see no solutions to this issue
