### ISSUE TITLE
ValorantCC Isn't opening

### ISSUE THREAD

**Issue by Kracioz** [weedeej/ValorantCC#29]
I've installed the .net thingy and valorantcc but when i open valorant cc it comes with this
![image](https://user-images.githubusercontent.com/111159723/184458005-3a28425b-cf85-4531-a329-c119e04ae400.png)

**Comment by weedeej** [comment]
> I've installed the .net thingy and valorantcc but when i open valorant cc it comes with this ![image](https://user-images.githubusercontent.com/111159723/184458005-3a28425b-cf85-4531-a329-c119e04ae400.png)

https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.2-windows-x64-installer

**Comment by jakerap** [comment]
dotnet 6.0.8 didn't work for me, but 6.0.2 worked flawlessly
