### ISSUE TITLE
Crashes after a while of use

### ISSUE THREAD

**Issue by eiden2233** [weedeej/ValorantCC#33]
Crashed once while using and since crashing at launch.
![image](https://user-images.githubusercontent.com/76058109/188953872-dcc0383f-afed-455b-826d-d30002d6dd25.png)

**Comment by weedeej** [comment]
https://appuals.com/how-to-fix-application-error-0xe0434352-on-windows/#:~:text=You%20may%20encounter%20the%20error,to%20load%20its%20essential%20components. not valorantcc related.

**Comment by eiden2233** [comment]
> https://appuals.com/how-to-fix-application-error-0xe0434352-on-windows/#:~:text=You%20may%20encounter%20the%20error,to%20load%20its%20essential%20components. not valorantcc related.

The error does not occur on a different account. I receive the "Your session expired!" on the other account.

From the website you linked, it seems like the error is just the application failing when calling upon a corrupt dependency. You cannot rule out that it is valorantcc related.

My guess according to my situation is the following: The lockfile of the account was corrupted by the program and is unable to be read now. 

You may try to replicate the issue by clicking on save multiple times, applying a few different community profiles.

**Comment by weedeej** [comment]
Hi again,
The program does not modify the lockfile. It only reads it like a normal text file. The guess is invalid. But I'll try to replicate using the steps you provided. The "Your session expired" issue is now being investigated.

**Comment by eiden2233** [comment]
Still crashing with that error on the account.
