### ISSUE TITLE
"Your session expired!"

### ISSUE THREAD

**Issue by FriedNori** [weedeej/ValorantCC#34]
After adjust colours of each crosshair and pressing save, it gives me the your session expired restart valorantcc/valorant every time 
![image_2022-09-07_223419143](https://user-images.githubusercontent.com/113078488/189020703-87e05e19-7cde-4bd3-a416-5f33121255ac.png)

**Comment by weedeej** [comment]
I'll investigate this.

**Comment by Banila48** [comment]
I have the same issue as well today

**Comment by weedeej** [comment]
Temporary fix applied on the latest update https://github.com/weedeej/ValorantCC/commit/bf7274ab8880294360c877be6425cdc255098d4c#diff-a2e7dcae63c695521b7db9d752d9d7baf6a9cc933aaa0fb4958df654f445d401R91
